// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package cart

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CartItem struct {
	UserID pgtype.Int8 `json:"user_id"`
	Sku    pgtype.Int8 `json:"sku"`
	Name   pgtype.Text `json:"name"`
	Price  pgtype.Int4 `json:"price"`
	Count  pgtype.Int4 `json:"count"`
}
