// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package cart

import (
	"context"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) error
	DeleteItem(ctx context.Context, arg DeleteItemParams) error
	DeleteItemByUser(ctx context.Context, userID int64) error
	GetItemsByUserID(ctx context.Context, userID int64) ([]CartItem, error)
}

var _ Querier = (*Queries)(nil)
