// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package cart

import (
	"context"
)

type Querier interface {
	AddCartItem(ctx context.Context, arg AddCartItemParams) error
}

var _ Querier = (*Queries)(nil)
