version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    depends_on:
      - loms
    environment:
      - LOMS_SERVICE_URL=loms:8082
      - PRODUCT_SERVICE_URL=route256.pavl.uk:8082
      - GRPC_ADDR=:8082
      - GRPC_GW_ADDR=:8080
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8083:8080"
    environment:
      - GRPC_ADDR=:8082
      - GRPC_GW_ADDR=:8080

  # databases
  loms-pgbouncer:
    image: edoburu/pgbouncer
    container_name: loms-pgbouncer
    ports:
      - "6432:6432"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=passwd
      - DB_HOST=loms-db
      - DB_NAME=postgres
      - LISTEN_ADDR=*
      - LISTEN_PORT=6432
      - ADMIN_USERS=postgres
      - POOL_MODE=transaction
      # In some cases md5 not work
      - AUTH_TYPE=plain
    depends_on:
      - loms-db

  loms-db:
    image: postgres:16.0
    container_name: loms-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data

  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
