version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    depends_on:
      - cart-pgbouncer
      - loms
    environment:
      - LOMS_SERVICE_URL=loms:8082
      - PRODUCT_SERVICE_URL=route256.pavl.uk:8082
      - GRPC_ADDR=:8082
      - GRPC_GW_ADDR=:8080
      - DATABASE_DSN=postgresql://postgres:passwd@cart-pgbouncer:6432/postgres
      - LIST_ITEM_SERVICE_WORKERS=2
      - PRODUCT_SERVICE_RPS=10

  loms:
    image: loms
    build: ./loms/
    ports:
      - "8083:8080"
    environment:
      - GRPC_ADDR=:8082
      - GRPC_GW_ADDR=:8080
      - DATABASE_DSN=postgresql://postgres:passwd@loms-pgbouncer:6432/postgres
    depends_on:
      - loms-pgbouncer

  # databases
  loms-pgbouncer:
    image: edoburu/pgbouncer
    container_name: loms-pgbouncer
    ports:
      - "6432:6432"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=passwd
      - DB_HOST=loms-db
      - DB_NAME=postgres
      - LISTEN_ADDR=*
      - LISTEN_PORT=6432
      - ADMIN_USERS=postgres
      # in this mode goose down doesn't work correct
      # - POOL_MODE=transaction
      # In some cases md5 not work, can't auth
      - AUTH_TYPE=plain
    depends_on:
      - loms-db

  loms-db:
    image: postgres:16.0
    container_name: loms-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgresql/loms-data:/var/lib/postgresql/data

  cart-pgbouncer:
    image: edoburu/pgbouncer
    container_name: cart-pgbouncer
    ports:
      - "7432:6432"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=passwd
      - DB_HOST=cart-db
      - DB_NAME=postgres
      - LISTEN_ADDR=*
      - LISTEN_PORT=6432
      - ADMIN_USERS=postgres
      # in this mode goose down doesn't work correct
      # - POOL_MODE=transaction
      # In some cases md5 not work, can't auth
      - AUTH_TYPE=plain
    depends_on:
      - cart-db

  cart-db:
    image: postgres:16.0
    container_name: cart-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passwd
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgresql/cart-data:/var/lib/postgresql/data

  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
