version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8080"
    depends_on:
      - loms
    environment:
      - LOMS_SERVICE_URL="http://loms:8080"
      - PRODUCT_SERVICE_URL="http://route256.pavl.uk:8080"
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8083:8080"
    environment:
      - ADDR=":8083"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
