version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "8082:8082"
    depends_on:
      - loms
    environment:
      - LOMS_SERVICE_URL=http://loms:82
      - PRODUCT_SERVICE_URL=http://route256.pavl.uk:8082
      - ADDR=:8082
  loms:
    image: loms
    build: ./loms/
    ports:
      - "8083:8082"
    environment:
      - ADDR=:8082
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
