// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package stock

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ReservedStock struct {
	UserID pgtype.Int8 `json:"user_id"`
	Sku    pgtype.Int8 `json:"sku"`
	Count  pgtype.Int8 `json:"count"`
}
