// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: stock.sql

package stock

import (
	"context"
)

const getBySKU = `-- name: GetBySKU :one
select available - total_reserved from stock
where sku = $1
`

func (q *Queries) GetBySKU(ctx context.Context, sku int64) (int32, error) {
	row := q.db.QueryRow(ctx, getBySKU, sku)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reserveCancel = `-- name: ReserveCancel :exec
update stock 
set available = available + $1,
    total_reserved = total_reserved - $1
where sku = $2
`

type ReserveCancelParams struct {
	Available int64 `json:"available"`
	Sku       int64 `json:"sku"`
}

func (q *Queries) ReserveCancel(ctx context.Context, arg ReserveCancelParams) error {
	_, err := q.db.Exec(ctx, reserveCancel, arg.Available, arg.Sku)
	return err
}

const reserveRemove = `-- name: ReserveRemove :exec
update stock
set total_reserved = total_reserved - $1
where sku = $2
`

type ReserveRemoveParams struct {
	TotalReserved int64 `json:"total_reserved"`
	Sku           int64 `json:"sku"`
}

func (q *Queries) ReserveRemove(ctx context.Context, arg ReserveRemoveParams) error {
	_, err := q.db.Exec(ctx, reserveRemove, arg.TotalReserved, arg.Sku)
	return err
}

const reserveStock = `-- name: ReserveStock :one
update stock 
set available = available - $1,
    total_reserved = total_reserved + $1
where sku = $2
returning available
`

type ReserveStockParams struct {
	Available int64 `json:"available"`
	Sku       int64 `json:"sku"`
}

func (q *Queries) ReserveStock(ctx context.Context, arg ReserveStockParams) (int64, error) {
	row := q.db.QueryRow(ctx, reserveStock, arg.Available, arg.Sku)
	var available int64
	err := row.Scan(&available)
	return available, err
}
