// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package orders

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID        int64              `json:"id"`
	UserID    pgtype.Int8        `json:"user_id"`
	StatusID  pgtype.Int4        `json:"status_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
