// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package order

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserOrder struct {
	ID     int64       `json:"id"`
	UserID pgtype.Int8 `json:"user_id"`
	Status pgtype.Text `json:"status"`
}
