// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package order

import (
	"context"
)

type Querier interface {
	AddOrderItem(ctx context.Context, arg AddOrderItemParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error)
	GetOrderByID(ctx context.Context, id int64) (UserOrder, error)
	SetStatus(ctx context.Context, arg SetStatusParams) error
}

var _ Querier = (*Queries)(nil)
